name: "Run Script and Comment on Commit"

# Trigger on pushes to any branch
on:
  push:
    branches:
      - main
    paths:
      - "locadex/**"

jobs: 
  run-script-and-comment:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Generate App Token (THIS WAS MISSING!)
      - name: Generate App Token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      # Step 2: Checkout the code from the production repo
      - name: Checkout Production Code
        uses: actions/checkout@v4
        with:
          path: production-repo
          token: ${{ steps.generate_token.outputs.token }} # Use the generated token

      # Step 3: Checkout the private test repo using the SSH key
      - name: Checkout Private Script Repo
        uses: actions/checkout@v4
        with:
          repository: SamEggert/grader-bot-test
          path: private-repo
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY_FOR_TESTS }}

      # Step 4: Run your private script and capture output
      - name: Run Script and Capture Output
        id: run-script
        run: |
          echo "Setting up script environment..."
          chmod +x private-repo/my_cli.sh
          
          echo "Running script..."
          output=$(./private-repo/my_cli.sh --target ./production-repo 2>&1)
          
          echo "script_output<<EOF" >> $GITHUB_OUTPUT
          echo "$output" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      # Step 5: Post comment on the commit
      - name: Comment on Commit
        uses: actions/github-script@v7
        with:
          github-token: ${{ steps.generate_token.outputs.token }} # Use the generated token, not the raw private key!
          script: |
            const output = `${{ steps.run-script.outputs.script_output }}`;
            
            const commentBody = `## Script Output
            
            \`\`\`
            ${output}
            \`\`\`
            
            _Generated by automated script on commit ${context.sha.substring(0, 8)}_`;
            
            await github.rest.repos.createCommitComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: context.sha,
              body: commentBody
            });