name: "Run Script and Comment on Commit"

on:
  push:
    branches:
      - main
    paths:
      - "locadex/**"

jobs: 
  run-script-and-comment:
    runs-on: ubuntu-latest
    steps:
      # Debug: Check APP_ID
      - name: Debug App ID
        run: |
          echo "App ID: ${{ secrets.APP_ID }}"
          echo "App ID length: ${#APP_ID}"
        env:
          APP_ID: ${{ secrets.APP_ID }}

      # Test: Check if app is installed
      - name: Test App Installation
        run: |
          echo "Checking app installation..."
          # This should return 200 if app is properly installed
          curl -v -H "Accept: application/vnd.github.v3+json" \
               -H "User-Agent: GitHub-Actions" \
               "https://api.github.com/repos/SamEggert/bot-test-public/installation" || echo "Installation check failed"

      # Step 1: Generate App Token
      - name: Generate App Token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          repositories: |
            bot-test-public
            grader-bot-test

      # Step 1.5: Debug - Test the token
      - name: Test GitHub App Token
        run: |
          echo "Testing token access..."
          echo "Testing public repo access:"
          curl -H "Authorization: token ${{ steps.generate_token.outputs.token }}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/SamEggert/bot-test-public
          echo -e "\n\nTesting private repo access:"
          curl -H "Authorization: token ${{ steps.generate_token.outputs.token }}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/SamEggert/grader-bot-test

      # Step 2: Checkout the public production repo using the App's token
      - name: Checkout Production Code
        uses: actions/checkout@v4
        with:
          path: production-repo
          token: ${{ steps.generate_token.outputs.token }}

      # Step 3: Checkout the private test repo using the SAME App's token
      - name: Checkout Private Script Repo
        uses: actions/checkout@v4
        timeout-minutes: 5  # Add timeout to prevent hanging
        with:
          repository: SamEggert/grader-bot-test
          path: private-repo
          token: ${{ steps.generate_token.outputs.token }}
          ref: main  # Explicitly specify the branch

      # Step 4: Run your private script
      - name: Run Script and Capture Output
        id: run-script
        run: |
          chmod +x private-repo/my_cli.sh
          output=$(./private-repo/my_cli.sh --target ./production-repo 2>&1)
          echo "script_output<<EOF" >> $GITHUB_OUTPUT
          echo "$output" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      # Step 5: Post comment on the commit
      - name: Comment on Commit
        uses: actions/github-script@v7
        with:
          github-token: ${{ steps.generate_token.outputs.token }}
          script: |
            const output = `${{ steps.run-script.outputs.script_output }}`;
            const commentBody = `## Script Output\n\n\`\`\`\n${output}\n\`\`\`\n\n_Generated by automated script on commit ${context.sha.substring(0, 8)}_`;
            await github.rest.repos.createCommitComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: context.sha,
              body: commentBody
            });